import Header from "./_layout/Header";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex">
        <Header />
        <div className="flex-grow  lg:ml-[30%] xl:ml-[20%]">{children}</div>
      </body>
    </html>
  );
}
